### ISSUE TITLE
which version of vtk to use?

### ISSUE THREAD

**Issue by zoez526** [IGSIO/IGSIO#10]
Hello, 

I'm wondering which version of vtk is used by this project?

Thanks,
Zoe

**Comment by Sunderlandkyl** [comment]
This project requires VTK 8+.

**Comment by zoez526** [comment]
Thanks for the reply!

Is it possible to change the default version of vtk in PlusBuild/SuperBuild/External_vtk.cmake to v8.0.0 then?  The current default is 7.1.0 and is causing compilation errors in vtkIGSIOTrackedFrameList.cxx when building PlusBuild-->ALL_BUILD in visual studio.

**Comment by Sunderlandkyl** [comment]
Already done: https://github.com/PlusToolkit/PlusBuild/commit/e373c12712dfc2d54b8b2dad1f4e3ee2380df1be. Plus 7.1.0 support has been removed.

You'll likely have to update PlusBuild and rebuild.

**Comment by zoez526** [comment]
> Already done: [PlusToolkit/PlusBuild@e373c12](https://github.com/PlusToolkit/PlusBuild/commit/e373c12712dfc2d54b8b2dad1f4e3ee2380df1be). Plus 7.1.0 support has been removed.
> 
> You'll likely have to update PlusBuild and rebuild.

Thanks!
