### ISSUE TITLE
Compile error on vtkIGSIOTrackedFrameList.cxx

### ISSUE THREAD

**Issue by fergujm2** [IGSIO/IGSIO#11]
MSVS2010, Win32, Release, VTK7

When building from PlusBuild with the above configuration, I get multiple compile errors at vtkIGSIOTrackedFrameList.cxx.

In the top level CMakeLists of PlusBuild, I switched to pull the IGSIO repository from this commit: 
https://github.com/IGSIO/IGSIO/commit/a5407f450f174a4762ef087dfe77ec5775d4df81
instead of master, and the problem is now gone.

I believe the issue is with the following commit where some changes were made to this class: https://github.com/IGSIO/IGSIO/commit/3580f7654a5574d767ae247a403df3b2aa55ba64

**Comment by Sunderlandkyl** [comment]
Plus no longer supports VS2010 or VTK7, the minimum recommended VisualStudio is 2015.

Try updating PlusBuild and compiling from scratch.

**Comment by fergujm2** [comment]
I am building with VS2010 to support a device with 2010 binaries, otherwise I would. I am just letting you all know in case the changes from that commit may affect something else. I will close the issue.

**Comment by adamrankin** [comment]
@Sunderlandkyl @lassoan We can't drop 2010 until Stealthlink switches?

**Comment by Sunderlandkyl** [comment]
The stealthlink guys say they have a VS2017 binary.
I've been trying to extract it from them.

They've already provided me with VS2013 libraries, but the switch to ITK5 has imposed a hard VS2015 restriction.

**Comment by Sunderlandkyl** [comment]
@fergujm2 Out of curiosity, what device are you trying to build?

**Comment by adamrankin** [comment]
Then let's roll back to ITKv4. We use a single class from ITK in all of Plus, and it hasn't changed in a looooonnng time.

**Comment by lassoan** [comment]
We plan to move most algorithms to IGSIO and use it both in Plus and in Slicer extensions. So, it is important that we can use the same ITK version as Slicer.

**Comment by fergujm2** [comment]
https://github.com/Sunderlandkyl I am working to get the IntuitiveDaVinci device working with our clinical machine at Vanderbilt. I had to do substantial work on the source though. I don’t think it was supposed to be fully implemented. The binaries that intuitive distributes with its collaborators are all built with VS2010.

**Comment by lassoan** [comment]
I don't think we can let a few device manufacturers dictate us to use 9-10 year old technology. For StealthLink there is a hope of getting new DLLs. We should ask Intuitive, too, maybe they have more recent DLLs, too (or they are willing to give us DLLs with C interface, which work with any VS version).

Maybe a good temporary solution could be to make ITK optional (if disabled then calibration algorithms will not be available).
