### ISSUE TITLE
VTKaddon

### ISSUE THREAD

**Issue by felixnavarro** [IGSIO/IGSIO#14]
Dear all, 

I'm trying to compile this lib because it is required by PlusLIB. When I try to configure the downloaded code (CMake 3.14.3 & MS Visual Studio 2019 on Windows) I get the following error:

```
Could not find a package configuration file provided by "vtkAddon" with any
  of the following names:

    vtkAddonConfig.cmake
    vtkaddon-config.cmake
```
Is there a workaround for this? 
I have not found the original vtkAddon library to build it.

**Comment by adamrankin** [comment]
I thought this was a CMake superbuild option somewhere, @Sunderlandkyl is this in Plus superbuild?

**Comment by felixnavarro** [comment]
Does any of you any workaround for this?

**Comment by adamrankin** [comment]
Yes, you'll have to build vtkAddon. It is done for you in the IGSIO superbuild. If you open up the superbuild solution, do you see a vtkAddon project?

Do you see a vtkAddon folder in the IGSIO-bin folder?

**Comment by felixnavarro** [comment]
Hi Adam, the CMake project works fine when the option IGSIO_SUPERBUILD variable is checked (CMake 3.14.3). 
Whe the project is generated and opened in Visual Studio 2019 the only solutions that I can select are: Debug (fails does not build any binary files,
[Debug_All_Build.txt](https://github.com/IGSIO/IGSIO/files/3210867/Debug_All_Build.txt)
 ), Release (works, [Release_ALL_BUILD.txt](https://github.com/IGSIO/IGSIO/files/3210834/Release_ALL_BUILD.txt), MinSizeRel, RelWithDebugInfo (fails, but build some binary files).

I can see the vtkAddon.dll and vtkAddon.lib in the bin\Release folder, but not in the folder for other configurations.

**Comment by adamrankin** [comment]
Plus isn't validated against VS 2019. @Sunderlandkyl do we know if it works?

**Comment by lassoan** [comment]
I've accidentally tried to build Plus on VS2019 with VS2019 toolset a few weeks ago. ITK build failed. Maybe latest ITK master is compatible, I haven't tested.

@felixnavarro You can still use VS2019 IDE (we use that, too), but make sure to specify VS2015 toolset (-T v140).

**Comment by felixnavarro** [comment]
ITK and VTK build with VS2019. VS2015 failed, I'll try again on Monday and inform you about the results of the compilation using VS2015.

**Comment by lassoan** [comment]
I've compiled Plus with VS2019 with VS2015 toolset from scratch on a new computer 2 weeks ago, by running these 3 lines on the command-line:

```
cd /d c:\D\PlusExp-x64-bin
"c:\Program Files\CMake\bin\cmake.exe" c:\D\PlusExp-build -G "Visual Studio 16 2019" -A x64 -T v140 -DQt5_DIR:PATH=C:/Qt/5.9.8/msvc2015_64/lib/cmake/Qt5 -DGIT_EXECUTABLE="c:\Program Files\Git\cmd\git.exe" -DPLUS_USE_3dConnexion_TRACKER:BOOL=ON -DPLUS_USE_Ascension3DG:BOOL=OFF -DPLUS_USE_Ascension3DGm:BOOL=OFF -DPLUS_USE_BKPROFOCUS_VIDEO:BOOL=OFF -DPLUS_USE_BRACHY_TRACKER:BOOL=OFF -DPLUS_USE_CERTUS:BOOL=OFF -DPLUS_USE_EPIPHAN:BOOL=OFF -DPLUS_USE_ICCAPTURING_VIDEO:BOOL=ON -DPLUS_USE_INTERSON_VIDEO:BOOL=OFF -DPLUS_USE_MICRONTRACKER:BOOL=ON -DPLUS_USE_MMF_VIDEO:BOOL=ON -DPLUS_USE_PHIDGET_SPATIAL_TRACKER:BOOL=OFF -DPLUS_USE_POLARIS:BOOL=ON -DPLUS_USE_ULTRASONIX_VIDEO:BOOL=OFF -DPLUS_USE_VFW_VIDEO:BOOL=ON
c:\D\PlusExp-x64-bin>"c:\Program Files\CMake\bin\ctest.exe" -D Experimental -C Release
```

Start a completely clean build, configure PlusBuild using CMake command-line arguments (-D...) to make sure that you can make changes in a reproducible way. If you still have issues, send us the command-line arguments you used and the build log.

**Comment by felixnavarro** [comment]
Dear Andras, I have executed the following command afteer including the path for several libraries (vtk, itk, igsio, vtkaddon) requested in the result of your command:
`c:\lib\bin\PlusLib-2.6.0clean>"c:\Program Files\CMake\bin\cmake.exe" C:/lib/src/PlusLib-clean -G "Visual Studio 16 2019"
 -A x64 -T v140 -DQt5_DIR:PATH=C:/programas/Qt/5.12.3/msvc2017_64/lib/cmake/Qt5 -DGIT_EXECUTABLE="C:/programas/Git/cmd/g
it.exe" -DPLUS_USE_3dConnexion_TRACKER:BOOL=OFF -DPLUS_USE_Ascension3DG:BOOL=OFF -DPLUS_USE_Ascension3DGm:BOOL=OFF -DPLU
S_USE_BKPROFOCUS_VIDEO:BOOL=OFF -DPLUS_USE_BRACHY_TRACKER:BOOL=ON -DPLUS_USE_CERTUS:BOOL=OFF -DPLUS_USE_EPIPHAN:BOOL=OFF
 -DPLUS_USE_ICCAPTURING_VIDEO:BOOL=OFF -DPLUS_USE_INTERSON_VIDEO:BOOL=OFF -DPLUS_USE_MICRONTRACKER:BOOL=OFF -DPLUS_USE_M
MF_VIDEO:BOOL=ON -DPLUS_USE_PHIDGET_SPATIAL_TRACKER:BOOL=OFF -DPLUS_USE_POLARIS:BOOL=OFF -DPLUS_USE_ULTRASONIX_VIDEO:BOO
L=OFF -DPLUS_USE_VFW_VIDEO:BOOL=ON -DVTK_DIR:PATH=C:/lib/bin/VTK-8.2.0 -DITK_DIR:PATH=C:/lib/bin/InsightToolkit-4.13.2 -
DIGSIO_DIR:PATH=C:/lib/bin/IGSIO -DvtkAddon_DIR:PATH=C:/lib/bin/IGSIO/vtkAddon-bin -DCMAKE_PREFIX_PATH:PATH=C:/lib/bin/I
GSIO/vtkAddon-bin`

I obtain the following log file
[CMakeOutput.log](https://github.com/IGSIO/IGSIO/files/3241133/CMakeOutput.log)

commandline output
[Commandline output.txt](https://github.com/IGSIO/IGSIO/files/3241147/Commandline.output.txt)

and cache file
[CMakeCache.txt](https://github.com/IGSIO/IGSIO/files/3241151/CMakeCache.txt)

**Comment by lassoan** [comment]
Please use the exact same build folder names and command line as I suggested. Yours have many mistakes (extra spaces, unnecessary arguments, etc. that break things).

**Comment by felixnavarro** [comment]
Using the same folder and command line this is the output.
[Commandline output.txt](https://github.com/IGSIO/IGSIO/files/3241251/Commandline.output.txt)
[CMakeOutput.log](https://github.com/IGSIO/IGSIO/files/3241253/CMakeOutput.log)

**Comment by lassoan** [comment]
Can you copy-paste your command line here?

**Comment by felixnavarro** [comment]
c:\D\PlusExp-x64-bin>"c:\Program Files\CMake\bin\cmake.exe" c:\D\PlusExp-build -G "Visual Studio 16 2019" -A x64 -T v140
 -DQt5_DIR:PATH=C:/Qt/5.9.8/msvc2015_64/lib/cmake/Qt5 -DGIT_EXECUTABLE="c:\Program Files\Git\cmd\git.exe" -DPLUS_USE_3dC
onnexion_TRACKER:BOOL=ON -DPLUS_USE_Ascension3DG:BOOL=OFF -DPLUS_USE_Ascension3DGm:BOOL=OFF -DPLUS_USE_BKPROFOCUS_VIDEO:
BOOL=OFF -DPLUS_USE_BRACHY_TRACKER:BOOL=OFF -DPLUS_USE_CERTUS:BOOL=OFF -DPLUS_USE_EPIPHAN:BOOL=OFF -DPLUS_USE_ICCAPTURIN
G_VIDEO:BOOL=ON -DPLUS_USE_INTERSON_VIDEO:BOOL=OFF -DPLUS_USE_MICRONTRACKER:BOOL=ON -DPLUS_USE_MMF_VIDEO:BOOL=ON -DPLUS_
USE_PHIDGET_SPATIAL_TRACKER:BOOL=OFF -DPLUS_USE_POLARIS:BOOL=ON -DPLUS_USE_ULTRASONIX_VIDEO:BOOL=OFF -DPLUS_USE_VFW_VIDE
O:BOOL=ON

**Comment by lassoan** [comment]
OK, so it looks mostly good now. The issue is that Plus tries to parse the current date (to create package name) and it fails. Probably it is due to your special (Spanish?) locale settings. 
Could you please add in c:\D\PlusExp-x64-bin\PlusLib\CMakeLists.txt file, above line 106 (`STRING(REGEX MATCH "([0-9])+-([0-9]+)-([0-9]+)" PLUSLIB_COMMIT_DATE ${_git_show_output})`) this command:

    message(WARNING "PLUSLIB_COMMIT_DATE=${PLUSLIB_COMMIT_DATE}")

and copy here the `PLUSLIB_COMMIT_DATE=…` line from the build output?

**Comment by felixnavarro** [comment]
Dear Andaras, there is not c:\D\PlusExp-x64-bin\**PlusLib** folder so I modified the c:\D\PlusExp-Build\CmakeLists.txt whose line 106 match with the code that you mention. I inserted the warning and I got this output:

> CMake Warning at CMakeLists.txt:106 (message):
>   _git_show_output=
> 
> CMake Error at CMakeLists.txt:107 (STRING):
>   STRING sub-command REGEX, mode MATCH needs at least 5 arguments total to
>   command.
> 
> CMake Error at CMakeLists.txt:108 (STRING):
>  STRING sub-command REPLACE requires at least four arguments.
>  
> CMake Error at src/CMakeLists.txt:3 (FIND_PACKAGE):
>   Could not find a package configuration file provided by "VTK" with any of
>   the following names:
> 
>   VTKConfig.cmake
>     vtk-config.cmake
> 
>   Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
>   to a directory containing one of the above files.  If "VTK" provides a
>   separate development package or SDK, be sure it has been installed.
> 
> -- Configuring incomplete, errors occurred!

If I type "date" on the commandline I get DD/MM/YYYY (DD=Day, MM=Month, YYYY=Year)

**Comment by lassoan** [comment]
[c:\D\PlusExp-Build\CmakeLists.txt](https://github.com/PlusToolkit/PlusBuild/blob/master/CMakeLists.txt#L106) should not contain `
STRING(REGEX MATCH "([0-9])+-([0-9]+)-([0-9]+)" PLUSLIB_COMMIT_DATE ${_git_show_output})`. If it does then something is very seriously wrong in your configuration. Make sure you always run the [3 commands to build Plus](https://github.com/IGSIO/IGSIO/issues/14#issuecomment-495619313) together (if you run the second line without first going to the right directory, you might mess up your build tree).

You should find the regex match line in [c:\D\PlusExp-bin\PlusLib\CMakeLists.txt](https://github.com/PlusToolkit/PlusLib/blob/master/CMakeLists.txt#L106). If you add the `message(WARNING "_git_show_output=${_git_show_output}")` command there then we should see the correct command output. If we see `_git_show_output=` (empty result) there then it probably means that git failed to execute, so you need to double-check the GIT_EXECUTABLE path in the second line of the build script. If the output is not empty then just its format is unexpected. You can then try to tune the [expression in line 102](https://github.com/PlusToolkit/PlusLib/blob/master/CMakeLists.txt#L102), replacing it with this:

    EXECUTE_PROCESS(COMMAND ${GIT_EXECUTABLE} show ${PLUSLIB_REVISION} -s --date=iso8601 --format=%cd

**Comment by felixnavarro** [comment]
Andas, 
I have re-dowloaded the code from [github](https://github.com/PlusToolkit/PlusLib.git) and performed a new clean build. I executed the cmake command from c:\D\PlusExp-x64-bin folder.
The result is the same, no PlusLib folder is created.in the binary folder and a CMakeLists.txt appears in PlusExp-Build since it is included in the zip file that I dowloaded (modification time remains to the time of the decompression after the execution of cmake). 

I attach the output of the cmake and ctest commands.

[CMakeOutput.log](https://github.com/IGSIO/IGSIO/files/3251558/CMakeOutput.log)
[ctestCommand_output.txt](https://github.com/IGSIO/IGSIO/files/3251559/ctestCommand_output.txt)
[cmakeCommand_output.txt](https://github.com/IGSIO/IGSIO/files/3251560/cmakeCommand_output.txt)

**Comment by lassoan** [comment]
You need to download and build [PlusBuild](https://github.com/PlusToolkit/PlusBuild) repository. It will download and build PlusLib and all dependencies.

**Comment by felixnavarro** [comment]
I'm asking to IT department to grant access to github, we are under a very restrictive firewall. This will take a few days.  :(

**Comment by lassoan** [comment]
Set PLUSBUILD_USE_GIT_PROTOCOL to OFF. It may help in getting through some firewalls.

**Comment by felixnavarro** [comment]
Dear Andras, sorry for the late reply but I've attended to our national congress.

I had to modify my installation of Visual Studio to include Git since cmake was reporting a problem with the version string of git.  After that the configuration process started to work.

The first time Cmake reported this:

> -- Could NOT find MicronTracker (missing: MicronTracker_LIBRARY MicronTracker_INCLUDE_DIR MicronTracker_BINARY_DIR)
CMake Error at CMakeLists.txt:573 (MESSAGE):
  This project requires Claron MicronTracker SDK for supporting the
  MicronTracker tracking device.  One of the components is missing.  Please
  verify configuration or turn off PLUS_USE_MICRONTRACKER.

I turned it off and Cmake reported:

> -- Could NOT find ICCAPTURING (missing: ICCAPTURING_INCLUDE_DIR ICCAPTURING_TIS_UDSHL_STATIC_LIB ICCAPTURING_TIS_UDSHL_S
HARED_LIB ICCAPTURING_TIS_UDSHLD_STATIC_LIB ICCAPTURING_TIS_UDSHLD_SHARED_LIB)
CMake Error at CMakeLists.txt:614 (MESSAGE):
  This project requires IC Capturing SDK for supporting the Imaging Source
  USB frame grabber.  One of the components is missing.  Please verify
  configuration or turn off PLUS_USE_ICCAPTURING_VIDEO.

I turned it off and turned on PLUS_USE_BRACHY_TRACKER since a CIVCO brachy stepper and a frame grabber (PLUS_USE_MMF_VIDEO) are the device that I inted to use. 

Everything worked fine.[WorkingCmakeOutput.txt](https://github.com/IGSIO/IGSIO/files/3271463/WorkingCmakeOutput.txt)

After that I executed the test:

> c:\D\PlusExp-x64-bin>"c:\Program Files\CMake\bin\ctest.exe" -D Experimental -C Release
   Site: PA-1RADIOF02
   Build name: vsx86-Windows-6.1.7601
Create new tag: 20190610-0914 - Experimental
Configure project
   Each . represents 1024 bytes of output
    . Size of output: 0K
Build project
   Each symbol represents 1024 bytes of output.
   '!' represents an error and '*' a warning.
    ..!!!! Size of output: 6K
Error(s) when building project
   5 Compiler errors
   1 Compiler warnings
Test project C:/D/PlusExp-x64-bin
No tests were found!!!
Performing coverage
 Cannot find any coverage files. Ignoring Coverage request.
Submit files
   SubmitURL: http://perkdata.cs.queensu.ca/CDash/submit.php?project=PlusBuild
   Submit failed, waiting 5 seconds...
   Retry submission: Attempt 1 of 3
   Submit failed, waiting 5 seconds...
   Retry submission: Attempt 2 of 3
   Submit failed, waiting 5 seconds...
   Retry submission: Attempt 3 of 3
   Error when uploading file: C:/D/PlusExp-x64-bin/Testing/20190610-0914/Configure.xml
   Error message was: Failed to connect to perkdata.cs.queensu.ca port 80: Timed out
   Problems when submitting via HTTP
Errors while running CTest

This is the file that cannot be sent: 
[Configure.xml.txt](https://github.com/IGSIO/IGSIO/files/3271495/Configure.xml.txt)

**Comment by lassoan** [comment]
Have you set PLUSBUILD_USE_GIT_PROTOCOL to OFF?

You can add ```DOWNLOAD_COMMAND ""``` to ```ExternalProject_Add``` to prevent downloading (cloning).

**Comment by felixnavarro** [comment]
For Windows users the configuration of git need to be modified using the following commands:
```
git config --global http.sslBackend openssl
git config --global http.sslVerify true
```
This way the code seems to compile correctly, I'll inform you about the results thown by the test command.

**Comment by lassoan** [comment]
We usually don't need to tweak these settings, but it is good to know that you had to, and happy to hear it fixed the network problems for you.

**Comment by felixnavarro** [comment]
I thought that the ctest was ok sin no ! appeared in the output but examining its build.xml log file  I can see this:

CMake Error at itk-prefix/tmp/itk-gitclone.cmake:75 (message):
    Failed to checkout tag: 'v5.00'

The whole Build.xml file is attached:
[build.xml.txt] (https://github.com/IGSIO/IGSIO/files/3311417/Build.xml.txt)

**Comment by Sunderlandkyl** [comment]
The issue with the ITK tag has been fixed. Try pulling the changes from PlusBuild.

**Comment by felixnavarro** [comment]
Sorry for the late reply, the compilation process was very long.
[Build.xml.txt](https://github.com/IGSIO/IGSIO/files/3311787/Build.xml.txt)

Let me translate a sentence related to one error for your convenience:

> símbolo externo _IsInitialized_ sin resolver al que se hace referencia en la función ....

means

> Unresolved external symbol _IsInitialized_  which is referenced in the fuction ....

This translation could be useful also:

>el tipo de máquina de biblioteca 'X86' está en conflicto con el tipo de máquina de destino 'x64'

means

>the machine of the library 'X86' is in conflict with the destination machine 'x64'

**Comment by Sunderlandkyl** [comment]
For the BrachyTracker device, the build needs to be 32-bit because the associated libraries are also 32-bit.

**Comment by felixnavarro** [comment]
If I change -A x64 for -A x86 I get 

 > This project doesn't contain the Configuration and Platform combination of Debug|Win32 

Is there an option to force the configuration to Release?

Complete command:
`"c:\Program Files\CMake\bin\cmake.exe" c:\D\PlusExp-build -G "Visual Studio 16 2019" -A x86 -T v140 -DQt5_DIR:PATH=C:/programas/Qt/5.12.3/msvc2017_64/lib/cmake/Qt5  -DGIT_EXECUTABLE="c:\programas\Git\cmd\git.exe" -DPLUS_USE_3dConnexion_TRACKER:BOOL=OFF -DPLUS_USE_Ascension3DG:BOOL=OFF -DPLUS_USE_Ascension3DGm:BOOL=OFF -DPLUS_USE_BKPROFOCUS_VIDEO:BOOL=OFF -DPLUS_USE_BRACHY_TRACKER:BOOL=ON -DPLUS_USE_CERTUS:BOOL=OFF -DPLUS_USE_EPIPHAN:BOOL=OFF -DPLUS_USE_ICCAPTURING_VIDEO:BOOL=OFF -DPLUS_USE_INTERSON_VIDEO:BOOL=OFF -DPLUS_USE_MICRONTRACKER:BOOL=OFF -DPLUS_USE_MMF_VIDEO:BOOL=ON -DPLUS_USE_PHIDGET_SPATIAL_TRACKER:BOOL=OFF -DPLUS_USE_POLARIS:BOOL=OFF -DPLUS_USE_ULTRASONIX_VIDEO:BOOL=OFF -DPLUS_USE_VFW_VIDEO:BOOL=ON`

**Comment by Sunderlandkyl** [comment]
Use -A Win32.
Because you are compiling with "-T v140", you will need to use the Visual Studio 2015 version of Qt.

**Comment by Sunderlandkyl** [comment]
Also, try updating PlusBuild again.
I added a fix that should help with Visual Studio 2019 builds (https://github.com/PlusToolkit/PlusBuild/commit/6bc8d7eb6f37039721ebae4914859a3ddd27420b).

**Comment by felixnavarro** [comment]
The compilation process has just ended successfully using the last version of the code and the version of QT that you recommended.

**Comment by felixnavarro** [comment]
The compilation process has just ended successfully using the last version of the code and the version of QT that you recommended. However, when I try to launch the server it crashes.
[062619_134343_PlusLog.txt](https://github.com/IGSIO/IGSIO/files/3329863/062619_134343_PlusLog.txt)

**Comment by Sunderlandkyl** [comment]
@felixnavarro Good to hear! Are there any other problems, or can this issue be closed?

**Comment by felixnavarro** [comment]
Everything is Ok, thanks.
