### ISSUE TITLE
VTKAddon

### ISSUE THREAD

**Issue by narayanakvs** [IGSIO/IGSIO#22]
I am trying to build IGSIO for the use in pluslib. 
I can use superbuild due to firewall isssues. 
while doing cmake configuration i am getting the following error 

of the following names:

    vtkAddonConfig.cmake
    vtkaddon-config.cmake

  Add the installation prefix of "vtkAddon" to CMAKE_PREFIX_PATH or set
  "vtkAddon_DIR" to a directory containing one of the above files.  If
  "vtkAddon" provides a separate development package or SDK, be sure it has
  been installed.

i have enabled vtkaddon while building vtk using cmake. Still gettig this error. I can see vtkaddon project.

**Comment by adamrankin** [comment]
IGSIO uses a custom fork of vtkAddon [here](https://github.com/Slicer/vtkAddon.git)

Clone and build that, the provide the bin directory to IGSIO cmake.
