### ISSUE TITLE
did the compile need ITK ?

### ISSUE THREAD

**Issue by whucsu** [IGSIO/IGSIO#30]
CMake Error at CMakeLists.txt:102 (FIND_PACKAGE):
  Could not find a package configuration file provided by "ITK" with any of
  the following names:

    ITKConfig.cmake
    itk-config.cmake

I install the VTK ,but no ITK..

**Comment by adamrankin** [comment]
Did you set ITK_DIR to the folder containing ITKConfig.cmake?
