### ISSUE TITLE
could not find TARGET vtkIGSIOCalibration

### ISSUE THREAD

**Issue by 1939938853** [IGSIO/IGSIO#31]
Hello,

I try to build IGSIO with vtk 9.1, when did cmake config, got "could not find TARGET vtkIGSIOCalibration".  Any solution for that?

Thank you!

`
CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/ExternalProject.cmake:3116 (get_property):
  get_property could not find TARGET vtkIGSIOCalibration.  Perhaps it has not
  yet been created.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.19/Modules/ExternalProject.cmake:3433 (_ep_add_configure_command)
  SuperBuild/External_vtkAddon.cmake:40 (ExternalProject_Add)
  SuperBuild/Superbuild.cmake:27 (INCLUDE)
  CMakeLists.txt:153 (INCLUDE)

CMake Error at C:/Program Files/CMake/share/cmake-3.19/Modules/ExternalProject.cmake:3116 (get_property):
  get_property could not find TARGET vtkIGSIOCalibration.  Perhaps it has not
  yet been created.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.19/Modules/ExternalProject.cmake:3433 (_ep_add_configure_command)
  SuperBuild/Superbuild.cmake:67 (ExternalProject_Add)
  CMakeLists.txt:153 (INCLUDE)
`

**Comment by Sunderlandkyl** [comment]
I just tested compiling a standalone IGSIO and haven't been able to reproduce yet.
Is this a standalone build or part of a SuperBuild project?

**Comment by 1939938853** [comment]
I have tried both builds. I'm using the latest vtkAddon from the slicer github site. That may be the cause.

**Comment by 1939938853** [comment]
The vtkAddon from the slicer github site, after build and install it just has lib and header file.  Can that be a problem.

**Comment by Sunderlandkyl** [comment]
The Slicer vtkAddon repository is correct. If you build IGSIO with IGSIO_SUPERBUILD enabled, it should automatically checkout and build the vtkAddon repository.

**Comment by 1939938853** [comment]
I think the problem might be

1. When I build and install vtkAddon in its install/cmake folder there is only vtkAddonConfig.cmake file. But IGSIO requires  vtkAddonTargets.cmake. I renamed it, it seems OK for IGSIO camke config and generate.
2.  When build IGSIO, it seems connot find vtkAddonConfigure.h. vtkAddon seems not generate  vtkAddonConfigure.h from  vtkAddonConfigure.h.in

**Comment by 1939938853** [comment]
Got it built. vtkAddon installation path related.
