### ISSUE TITLE
i construct cmake-gui question use in windows

### ISSUE THREAD

**Issue by Edward-hb** [IGSIO/IGSIO#33]
hi 
this is I pree configure then show there errors 
CMake Error at D:/LIB/VTK/vtk-prefix/lib/cmake/vtk-8.2/vtkModuleAPI.cmake:140 (message):
  Requested modules not available:

    vtkGUISupportQtWebkit
Call Stack (most recent call first):
  D:/LIB/VTK/vtk-prefix/lib/cmake/vtk-8.2/VTKConfig.cmake:143 (vtk_module_config)
  CMakeLists.txt:91 (FIND_PACKAGE)
i install vtk8.2 version and add vtk_DIR .How slove this error?

**Comment by adamrankin** [comment]
Does your build of VTK have Webkit enabled?

**Comment by lassoan** [comment]
Latest IGSIO master version is tested with VTK9. We don't actively maintain backward compatibility with VTK-8.2. If you want to use VTK-8.2 then you may need to go back to the IGSIO version of January 2021 of earlier.

**Comment by 212240447** [comment]
> Does your build of VTK have Webkit enabled?

Didn't notice this at the time，directly build project

**Comment by 212240447** [comment]
> Latest IGSIO master version is tested with VTK9. We don't actively maintain backward compatibility with VTK-8.2. If you want to use VTK-8.2 then you may need to go back to the IGSIO version of January 2021 of earlier.

thank you , i will reinstall olde version
