### ISSUE TITLE
Superbuild IGSIOConfig.cmake does not populate vtkAddon_DIR

### ISSUE THREAD

**Issue by adamrankin** [IGSIO/IGSIO#4]
Recommend removing superbuild creation of this file.

**Comment by Sunderlandkyl** [comment]
I agree, generation of IGSIOConfig.cmake is not supposed to happen for Superbuild, and in CMakeLists.txt, it is not supposed to be generated unless IGSIO_SUPERBUILD is false: https://github.com/IGSIO/IGSIO/blob/3a881ddc45852a54003a4d635718e11d88edb159/CMakeLists.txt#L124-L151

Do you have an idea why it might be generated anyways?

**Comment by adamrankin** [comment]
This code exists
```cmake
INCLUDE(CMakePackageConfigHelpers)
# Re: #1075 eventually remove this section after people are used to the new location
CONFIGURE_FILE(IGSIOConfig.cmake.in
  "${CMAKE_CURRENT_BINARY_DIR}/IGSIOConfig.cmake" @ONLY)
```
lines 67-71

**Comment by Sunderlandkyl** [comment]
Whoops, that's embarrassing. Not sure how I missed that.
